### ISSUE TITLE
[Question] How to keep the client alive?

### ISSUE THREAD

**Issue by dokiKit** [Qatja/qatja-android#27]
I am developing an application that requires the mqtt client to be alive and have a persistent connection during it's lifespan, and be able to reconnect when network recovers. When should I initialize the client ? Thanks.

**Comment by agoransson** [comment]
Keeping the app connected is a bit tricky in itself. Us mortal app developers can't really ever guarantee a connection will stay alive - when you have access to platform it's a whole different story. The short answer is 
> There doesn't exist one "true" place where you should attempt to initiate a connection (or tear it down for that matter). You need to monitor the state of the device and react according to its current state.

The long answer is too long to push into one comment, I'll assemble an example for you.

**Comment by agoransson** [comment]
Sorry, been a bit busy with work I totally forgot about this. And then I realised your usecase might involve a service running constantly, nomatter what. Then you should try a foreground service instead of a normal service. It's not a big difference.

Read more about it at https://developer.android.com/guide/components/services#Foreground
