### ISSUE TITLE
How to unsubscribe specific topic in qatja-android?

### ISSUE THREAD

**Issue by TPriyath** [Qatja/qatja-android#28]
I'm developing an android application using the qatja-android library. Is there any method to unsubscribe from the given topic?

**Comment by agoransson** [comment]
I haven't been looking at this lib myself for very long - considering it might not even work with current versions of android due to Google changing the way we're allowed to run background tasks. At lesat the example needs to be updated to reflect the need for a visible notification if the service should run in background.

The library does support unsubscribing - but looking at the service, it does not. I think the easiest way to get this to work, due to my build servers been taken offline (Travis-ci changed their servers) is if you just make your own copy of the service code, call it something else to avoid confusion.

Copy this code into a new class in your app.
https://github.com/Qatja/qatja-android/blob/master/qatja-android/src/main/java/se/wetcat/qatja/android/QatjaService.java

And add the required gradle dependencies (the MQTT core definitions):
```
    implementation 'se.wetcat.qatja:core:1.0.4'
```

Then simply add an `unsubscribe` function, following similar pattern as the `subscribe`... setting the identifier using the helper function. Hopefully that would do the trick for you. =) 

```
  /**
   * Subscribe to multiple topics
   *
   * @param topics Topic to subscribe to
   * @param qoss   Quality of service, can be {@link se.wetcat.qatja.MQTTConstants#AT_MOST_ONCE},
   *               {@link se.wetcat.qatja.MQTTConstants#AT_LEAST_ONCE}, or
   *               {@link se.wetcat.qatja.MQTTConstants#EXACTLY_ONCE}.
   */
  public void subscribe(String[] topics, byte[] qoss) {
    // Ensure the subscribedTopics isn't null
    if (subscribedTopics == null)
      subscribedTopics = new HashSet<>();

    for(int i = 0; i < topics.length; i++) {
      HashSet<String> newTopics = new HashSet<>();

      if(!subscribedTopics.contains(topics[i])) {
        newTopics.add(topics[i]);
      }
      topics = newTopics.toArray(new String[0]);
    }

    if(topics.length == 0) {
      return;
    }

    int id = mMqttIdentifierHelper.getIdentifier();

    MQTTSubscribe subscribe = MQTTSubscribe.newInstance(topics, qoss, id);
    sendMessage(subscribe);

    subscribedTopics.addAll(Arrays.asList(topics));

    mMqttIdentifierHelper.addSentPackage(subscribe);
  }
```

**Comment by agoransson** [comment]
The identifier is just a new unique number - or rather, a currently unused number.

**Comment by TPriyath** [comment]
Thank you for the reply. I implemented the following method for unsubscribing the topic and it works as expected.

public void unsubscribe(String[] topics) {

    if (subscribedTopics == null)
      return;

    for(int i = 0; i < topics.length; i++) {

      if(!subscribedTopics.contains(topics[i])) {
        return;
      }
    }

    if(topics.length == 0) {
      return;
    }

    int id = mMqttIdentifierHelper.getIdentifier();

    MQTTUnsubscribe unSubscribe = MQTTUnsubscribe.newInstance(id, topics);
    sendMessage(unSubscribe);

    subscribedTopics.removeAll(Arrays.asList(topics));

    mMqttIdentifierHelper.addSentPackage(unSubscribe);
  }
